version: 0.5.0-{build}

os: Visual Studio 2017

nuget:
  account_feed: false
  
branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

init:
- git config --global core.autocrlf true

before_build:
- cmd: dotnet restore

build_script:
- cmd: dotnet build src/Hangfire.Tags -c Release
- cmd: dotnet build src/Hangfire.Tags.SqlServer -c Release
- cmd: dotnet build tests/Hangfire.Tags.Tests -c Release
- cmd: dotnet build src/Hangfire.Tags.PostgreSql -c Release
- cmd: dotnet build tests/Hangfire.Tags.PostgreSql.Tests -c Release
- cmd: dotnet build src/Hangfire.Tags.MySql -c Release
- cmd: dotnet build tests/Hangfire.Tags.MySql.Tests -c Release
- cmd: dotnet build src/Hangfire.Tags.Redis.StackExchange -c Release

after_build:
- cmd: dotnet pack src/Hangfire.Tags -o ../../artifacts -c Release
- cmd: dotnet pack src/Hangfire.Tags.SqlServer -o ../../artifacts -c Release
- cmd: dotnet pack src/Hangfire.Tags.PostgreSql -o ../../artifacts -c Release
- cmd: dotnet pack src/Hangfire.Tags.MySql -o ../../artifacts -c Release
- cmd: dotnet pack src/Hangfire.Tags.Redis.StackExchange -o ../../artifacts -c Release

test_script:
- cmd: dotnet test tests/Hangfire.Tags.Tests/Hangfire.Tags.Tests.csproj
- cmd: dotnet test tests/Hangfire.Tags.PostgreSql.Tests/Hangfire.Tags.PostgreSql.Tests.csproj
- cmd: dotnet test tests/Hangfire.Tags.MySql.Tests/Hangfire.Tags.MySql.Tests.csproj

artifacts:
- path: 'artifacts/**/*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: DO/TE9Xkurlvb3bH1RQ+dJf4OtGr3AcfVQ793+hp1Yor19xI4hgWw1GOymW1kBB2
  skip_symbols: true
  on:
    branch: master
